### ISSUE TITLE
Error when conditionally not sending an email

### ISSUE THREAD

**Issue by alexQueue** [sendwithus/sendwithus_ruby_action_mailer#38] opened 2016-07-08 21:45 UTC
We have a welcome email that we just ported over that we choose not to send if the user cancels by the time the mail queue gets to them, but our mailer is raising `SendWithUs::ApiNilEmailId: email_id cannot be nil` when we try to return from the mailer without sending a mail.

e.g. 
```ruby
def welcome(user_id)
  user = User.find(user_id)
  return if user.canceled?
  
  mail(
      email_id: ...,
      version_name: ...,
      recipient_address: user.email
    )
end
```
raises if the user is canceled.

This seems like a bug considering the documentation here: https://github.com/sendwithus/sendwithus_ruby_action_mailer#conditional-delivery

**Comment by demoore** [comment] 2016-07-08 22:28
@alexQueue That is expected behaviour — API calls should fail if a template ID isn't supplied. I think something might be off on your end as our example never hits the `mail()` function. Have you tried putting in some logging before calling mail()?

**Comment by alexQueue** [comment] 2016-07-22 15:07
@demoore I don't believe that's correct. You don't supply a template id in your docs,
```ruby
    def we_miss_you(user_id)
        user = User.find user_id
        if user.do_we_miss_him?
            mail(
                email_id: 'ID-CODE-FROM-SEND-WITH-US',
                recipient_address: user.email
            )
        end
    end
```

With logging:
```ruby
def welcome(user_id)
  template_id = ...  
  user = User.find(user_id)
  puts 'Got to here'
  return if user.canceled?

  mail(
      email_id: ...,
      version_name: ...,
      recipient_address: user.email
    )
end
```
```
Got to here
SendWithUs::ApiNilEmailId: email_id cannot be nil
```

**Comment by demoore** [comment] 2016-07-22 15:52
@alexQueue I believe there's two issues here:

1. There's an invalid template ID being used. That's the `email_id` parameter, I'll make that clearer in the README.
2. `user.canceled?` is evaluating to something falsey and your method is skipping the return.

Try running this:
```ruby
def welcome(user_id)
  template_id = ...  
  user = User.find(user_id)
  return if user.canceled?

  puts 'Got past the return statement'
  puts user.canceled?

  mail(
      email_id: ...,
      version_name: ...,
      recipient_address: user.email
    )
end
```

**Comment by alexQueue** [comment] 2016-07-22 18:07
1. We're successfully sending emails with this template. The error is only where we return before the call to `mail`.

2. I've tested with an unconditional `return` and it errors.

```
"Before the return statement"
SendWithUs::ApiNilEmailId: email_id cannot be nil
```

**Comment by demoore** [comment] 2016-07-22 19:03
If you've tested with an unconditional return statement then it shouldn't be calling `mail`… Do you still get the error if you comment `mail(…)` out? It could be bubbling up from somewhere else.

**Comment by alexQueue** [comment] 2016-07-22 19:06
I think you've misunderstood me. This happens when I do not call `mail`, so commenting out the `mail(...)` will do the same thing. The issue is that `return`ing without calling `mail` causes this error (even though there's an example that does this in the docs)

**Comment by demoore** [comment] 2016-07-22 19:10
If it's not happening there, then it sounds to me like there's somewhere else in your code that's calling `mail()` without an email_id.

**Comment by alexQueue** [comment] 2016-07-22 19:16
I was suspicious it was due to our sidekiq setup or something like that, so I deleted all of that. Same problem.
```ruby
class SendWithUsUserNotifier < SendWithUsMailer::Base
  def welcome(user_id)
    p 'got here'
    return
    p 'and here'
  end
end  
```
...
`SendWithUsUserNotifier.welcome(1).deliver`
```
"got here"
SendWithUs::ApiNilEmailId: email_id cannot be nil
```

**Comment by demoore** [comment] 2016-07-22 20:48
So that seems super weird. I just loaded up a fresh rails project and couldn't reproduce the issue. Do you have the latest version of the gem installed? I know conditional delivery was only added recently (v0.3.1).

**Comment by alexQueue** [comment] 2016-07-22 21:18
Welp there it is. We're out of date and using v0.3.0

Sorry for that. Thanks for the help though!

**Comment by demoore** [comment] 2016-07-22 22:16
Haha, glad we got that sorted out 😄 . I'm closing the issue for now, but if it doesn't work in the latest version let me know.

**Closed by demoore** 2016-07-22 22:16 UTC
